#theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Sujata Roy
logo: "assets/img/GitHub_portfolio_pic.jpg?raw=true"
description: >
  <div style="text-align: center;">
      <a style="text-decoration:none" href="https://www.linkedin.com/in/sujata-roy/">
          <img src="https://cdn-icons-png.flaticon.com/128/3536/3536569.png" alt="LinkedIn" style="width: 30px; height: 30px; margin-right: 10px;">
      </a>
      <a style="text-decoration:none" href="https://github.com/Sujata2017">
  </div>
  <div style="text-align: center;">
      <p>GenAI Developer</p>
  </div>
